spring:
  datasource:
    driver-class-name: '${custom.local.database.driver-class-name}'
    url: '${custom.local.database.url}'
    username: '${custom.local.database.username}'
    password: '${custom.local.database.password}'
  data:
    redis:
      host: '${custom.local.redis.host}'
      port: '${custom.local.redis.port}'

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: '${custom.local.kakao-redirect-url}'
          naver:
            redirect-uri: '${custom.local.naver-redirect-url}'
          google:
            redirect-uri: '${custom.local.google-redirect-url}'

logging:
  level:
    root: INFO
    com.example.ot: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

server:
  servlet:
    context-path: '${custom.local.servlet.path}'
  port: '${custom.local.server.port}'

custom:
  url: '${custom.local.url}'