spring:
  datasource:
    driver-class-name: '${custom.prod.database.driver-class-name}'
    url: '${custom.prod.database.url}'
    username: '${custom.prod.database.username}'
    password: '${custom.prod.database.password}'
  data:
    redis:
      host: '${custom.prod.redis.host}'
      port: '${custom.prod.redis.port}'

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: '${custom.prod.kakao-redirect-url}'

server:
  servlet:
    context-path: '${custom.prod.servlet.path}'
  port: '${custom.prod.server.port}'

logging:
  discord:
    webhook-uri: '${custom.prod.webhook.logBack}'
  config: classpath:log/logback-spring.xml

custom:
  url: '${custom.prod.url}'