spring:
  datasource:
    driver-class-name: '${custom.dev.database.driver-class-name}'
    url: '${custom.dev.database.url}'
    username: '${custom.dev.database.username}'
    password: '${custom.dev.database.password}'
  data:
    redis:
      host: '${custom.dev.redis.host}'
      port: '${custom.dev.redis.port}'

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: '${custom.dev.kakao.redirect-url}'
          naver:
            redirect-uri: '${custom.dev.naver.redirect-url}'
          google:
            redirect-uri: '${custom.dev.google.redirect-url}'

server:
  servlet:
    context-path: '${custom.dev.servlet.path}'
  port: '${custom.dev.server.port}'

logging:
  discord:
    webhook-uri: '${custom.dev.webhook.logBack}'
  config: classpath:log/logback-spring.xml

custom:
  url: '${custom.dev.url}'