spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath:test_data_h2.sql
      mode: always

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: '${custom.local.kakao.redirect-url}'
          naver:
            redirect-uri: '${custom.local.naver.redirect-url}'
          google:
            redirect-uri: '${custom.local.google.redirect-url}'
custom:
  url: '${custom.local.url}'